// Level names and sidebar groups (ZELDA64.md §4.3-§4.4: decomp scene names, MM area titles) and actor names
// (decomp include/tables/actor_table.h; ids are the same in every version of a game). Generated from the spec.

import type { LevelKind } from '../types';

// [scene id, name, kind, group, scene file name], in sidebar order.
export type SceneName = [number, string, LevelKind, string, string];

export const OOT_SCENES: SceneName[] = [
  [0x51, 'Hyrule Field', 'hub', 'Hyrule Field and Castle', 'spot00_scene'],
  [0x63, 'Lon Lon Ranch', 'hub', 'Hyrule Field and Castle', 'spot20_scene'],
  [0x5F, 'Hyrule Castle', 'hub', 'Hyrule Field and Castle', 'spot15_scene'],
  [0x64, 'Outside Ganon\'s Castle', 'hub', 'Hyrule Field and Castle', 'ganon_tou_scene'],
  [0x1B, 'Market Entrance Day', 'hub', 'Castle Town', 'entra_scene'],
  [0x1C, 'Market Entrance Night', 'hub', 'Castle Town', 'entra_n_scene'],
  [0x1D, 'Market Entrance Ruins', 'hub', 'Castle Town', 'enrui_scene'],
  [0x1E, 'Back Alley Day', 'hub', 'Castle Town', 'market_alley_scene'],
  [0x1F, 'Back Alley Night', 'hub', 'Castle Town', 'market_alley_n_scene'],
  [0x20, 'Market Day', 'hub', 'Castle Town', 'market_day_scene'],
  [0x21, 'Market Night', 'hub', 'Castle Town', 'market_night_scene'],
  [0x22, 'Market Ruins', 'hub', 'Castle Town', 'market_ruins_scene'],
  [0x23, 'Temple Of Time Exterior Day', 'hub', 'Castle Town', 'shrine_scene'],
  [0x24, 'Temple Of Time Exterior Night', 'hub', 'Castle Town', 'shrine_n_scene'],
  [0x25, 'Temple Of Time Exterior Ruins', 'hub', 'Castle Town', 'shrine_r_scene'],
  [0x45, 'Castle Courtyard Guards Day', 'hub', 'Castle Town', 'hairal_niwa_scene'],
  [0x46, 'Castle Courtyard Guards Night', 'hub', 'Castle Town', 'hairal_niwa_n_scene'],
  [0x4A, 'Castle Courtyard Zelda', 'hub', 'Castle Town', 'nakaniwa_scene'],
  [0x55, 'Kokiri Forest', 'hub', 'Kokiri Forest and Lost Woods', 'spot04_scene'],
  [0x5B, 'Lost Woods', 'hub', 'Kokiri Forest and Lost Woods', 'spot10_scene'],
  [0x56, 'Sacred Forest Meadow', 'hub', 'Kokiri Forest and Lost Woods', 'spot05_scene'],
  [0x52, 'Kakariko Village', 'hub', 'Kakariko and Death Mountain', 'spot01_scene'],
  [0x53, 'Graveyard', 'hub', 'Kakariko and Death Mountain', 'spot02_scene'],
  [0x60, 'Death Mountain Trail', 'hub', 'Kakariko and Death Mountain', 'spot16_scene'],
  [0x61, 'Death Mountain Crater', 'hub', 'Kakariko and Death Mountain', 'spot17_scene'],
  [0x62, 'Goron City', 'hub', 'Kakariko and Death Mountain', 'spot18_scene'],
  [0x54, 'Zora\'s River', 'hub', 'Zora\'s River and Lake Hylia', 'spot03_scene'],
  [0x58, 'Zora\'s Domain', 'hub', 'Zora\'s River and Lake Hylia', 'spot07_scene'],
  [0x59, 'Zora\'s Fountain', 'hub', 'Zora\'s River and Lake Hylia', 'spot08_scene'],
  [0x57, 'Lake Hylia', 'hub', 'Zora\'s River and Lake Hylia', 'spot06_scene'],
  [0x5A, 'Gerudo Valley', 'hub', 'Gerudo', 'spot09_scene'],
  [0x5D, 'Gerudo\'s Fortress', 'hub', 'Gerudo', 'spot12_scene'],
  [0x5E, 'Haunted Wasteland', 'hub', 'Gerudo', 'spot13_scene'],
  [0x5C, 'Desert Colossus', 'hub', 'Gerudo', 'spot11_scene'],
  [0x00, 'Deku Tree', 'adventure', 'Dungeons', 'ydan_scene'],
  [0x01, 'Dodongos Cavern', 'adventure', 'Dungeons', 'ddan_scene'],
  [0x02, 'Jabu-Jabu\'s Belly', 'adventure', 'Dungeons', 'bdan_scene'],
  [0x03, 'Forest Temple', 'adventure', 'Dungeons', 'Bmori1_scene'],
  [0x04, 'Fire Temple', 'adventure', 'Dungeons', 'HIDAN_scene'],
  [0x05, 'Water Temple', 'adventure', 'Dungeons', 'MIZUsin_scene'],
  [0x06, 'Spirit Temple', 'adventure', 'Dungeons', 'jyasinzou_scene'],
  [0x07, 'Shadow Temple', 'adventure', 'Dungeons', 'HAKAdan_scene'],
  [0x08, 'Bottom of the Well', 'adventure', 'Dungeons', 'HAKAdanCH_scene'],
  [0x09, 'Ice Cavern', 'adventure', 'Dungeons', 'ice_doukutu_scene'],
  [0x0B, 'Gerudo Training Ground', 'adventure', 'Dungeons', 'men_scene'],
  [0x0C, 'Thieves Hideout', 'adventure', 'Dungeons', 'gerudoway_scene'],
  [0x0D, 'Inside Ganon\'s Castle', 'adventure', 'Dungeons', 'ganontika_scene'],
  [0x0A, 'Ganon\'s Tower', 'adventure', 'Dungeons', 'ganon_scene'],
  [0x0E, 'Ganon\'s Tower Collapse Interior', 'adventure', 'Dungeons', 'ganon_sonogo_scene'],
  [0x0F, 'Inside Ganon\'s Castle Collapse', 'adventure', 'Dungeons', 'ganontikasonogo_scene'],
  [0x1A, 'Ganon\'s Tower Collapse Exterior', 'adventure', 'Dungeons', 'ganon_final_scene'],
  [0x11, 'Deku Tree Boss', 'boss', 'Boss rooms', 'ydan_boss_scene'],
  [0x12, 'Dodongos Cavern Boss', 'boss', 'Boss rooms', 'ddan_boss_scene'],
  [0x13, 'Jabu-Jabu\'s Belly Boss', 'boss', 'Boss rooms', 'bdan_boss_scene'],
  [0x14, 'Forest Temple Boss', 'boss', 'Boss rooms', 'moribossroom_scene'],
  [0x15, 'Fire Temple Boss', 'boss', 'Boss rooms', 'FIRE_bs_scene'],
  [0x16, 'Water Temple Boss', 'boss', 'Boss rooms', 'MIZUsin_bs_scene'],
  [0x17, 'Spirit Temple Boss', 'boss', 'Boss rooms', 'jyasinboss_scene'],
  [0x18, 'Shadow Temple Boss', 'boss', 'Boss rooms', 'HAKAdan_bs_scene'],
  [0x19, 'Ganondorf Boss', 'boss', 'Boss rooms', 'ganon_boss_scene'],
  [0x4F, 'Ganon Boss', 'boss', 'Boss rooms', 'ganon_demo_scene'],
  [0x34, 'Link\'s House', 'other', 'Houses, shops and minigames', 'link_home_scene'],
  [0x26, 'Know-It-All Brothers\' House', 'other', 'Houses, shops and minigames', 'kokiri_home_scene'],
  [0x27, 'Twins\' House', 'other', 'Houses, shops and minigames', 'kokiri_home3_scene'],
  [0x28, 'Mido\'s House', 'other', 'Houses, shops and minigames', 'kokiri_home4_scene'],
  [0x29, 'Saria\'s House', 'other', 'Houses, shops and minigames', 'kokiri_home5_scene'],
  [0x2D, 'Kokiri Shop', 'other', 'Houses, shops and minigames', 'kokiri_shop_scene'],
  [0x2A, 'Kakariko Center Guest House', 'other', 'Houses, shops and minigames', 'kakariko_scene'],
  [0x2B, 'Back Alley House', 'other', 'Houses, shops and minigames', 'kakariko3_scene'],
  [0x35, 'Dog Lady House', 'other', 'Houses, shops and minigames', 'impa_scene'],
  [0x37, 'Impa\'s House', 'other', 'Houses, shops and minigames', 'labo_scene'],
  [0x30, 'Potion Shop Kakariko', 'other', 'Houses, shops and minigames', 'drag_scene'],
  [0x39, 'Carpenters\' Tent', 'other', 'Houses, shops and minigames', 'tent_scene'],
  [0x3A, 'Gravekeeper\'s Hut', 'other', 'Houses, shops and minigames', 'hut_scene'],
  [0x2C, 'Bazaar', 'other', 'Houses, shops and minigames', 'shop1_scene'],
  [0x31, 'Potion Shop Market', 'other', 'Houses, shops and minigames', 'alley_shop_scene'],
  [0x32, 'Bombchu Shop', 'other', 'Houses, shops and minigames', 'night_shop_scene'],
  [0x33, 'Happy Mask Shop', 'other', 'Houses, shops and minigames', 'face_shop_scene'],
  [0x2E, 'Goron Shop', 'other', 'Houses, shops and minigames', 'golon_scene'],
  [0x2F, 'Zora Shop', 'other', 'Houses, shops and minigames', 'zoora_scene'],
  [0x4E, 'Potion Shop Granny', 'other', 'Houses, shops and minigames', 'mahouya_scene'],
  [0x10, 'Treasure Box Shop', 'other', 'Houses, shops and minigames', 'takaraya_scene'],
  [0x42, 'Shooting Gallery', 'other', 'Houses, shops and minigames', 'syatekijyou_scene'],
  [0x4B, 'Bombchu Bowling Alley', 'other', 'Houses, shops and minigames', 'bowling_scene'],
  [0x49, 'Fishing Pond', 'other', 'Houses, shops and minigames', 'turibori_scene'],
  [0x50, 'House Of Skulltula', 'other', 'Houses, shops and minigames', 'kinsuta_scene'],
  [0x36, 'Stable', 'other', 'Houses, shops and minigames', 'malon_stable_scene'],
  [0x4C, 'Lon Lon Buildings', 'other', 'Houses, shops and minigames', 'souko_scene'],
  [0x4D, 'Market Guard House', 'other', 'Houses, shops and minigames', 'miharigoya_scene'],
  [0x38, 'Lakeside Laboratory', 'other', 'Houses, shops and minigames', 'hylia_labo_scene'],
  [0x43, 'Temple Of Time', 'other', 'Houses, shops and minigames', 'tokinoma_scene'],
  [0x44, 'Chamber of the Sages', 'other', 'Houses, shops and minigames', 'kenjyanoma_scene'],
  [0x3B, 'Great Fairy\'s Fountain Magic', 'other', 'Fairy fountains, grottos and graves', 'daiyousei_izumi_scene'],
  [0x3D, 'Great Fairy\'s Fountain Spells', 'other', 'Fairy fountains, grottos and graves', 'yousei_izumi_yoko_scene'],
  [0x3C, 'Fairy\'s Fountain', 'other', 'Fairy fountains, grottos and graves', 'yousei_izumi_tate_scene'],
  [0x3E, 'Grottos', 'other', 'Fairy fountains, grottos and graves', 'kakusiana_scene'],
  [0x3F, 'Redead Grave', 'other', 'Fairy fountains, grottos and graves', 'hakaana_scene'],
  [0x40, 'Grave With Fairy\'s Fountain', 'other', 'Fairy fountains, grottos and graves', 'hakaana2_scene'],
  [0x41, 'Royal Family\'s Tomb', 'other', 'Fairy fountains, grottos and graves', 'hakaana_ouke_scene'],
  [0x48, 'Windmill and Dampé\'s Grave', 'other', 'Fairy fountains, grottos and graves', 'hakasitarelay_scene'],
  [0x47, 'Cutmap', 'other', 'Cutscene map', 'hiral_demo_scene'],
  [0x65, 'Test01', 'other', 'Test maps (MQ debug only)', 'test01_scene'],
  [0x66, 'Besitu', 'other', 'Test maps (MQ debug only)', 'besitu_scene'],
  [0x67, 'Depth Test', 'other', 'Test maps (MQ debug only)', 'depth_test_scene'],
  [0x68, 'Syotes', 'other', 'Test maps (MQ debug only)', 'syotes_scene'],
  [0x69, 'Syotes2', 'other', 'Test maps (MQ debug only)', 'syotes2_scene'],
  [0x6A, 'Sutaru', 'other', 'Test maps (MQ debug only)', 'sutaru_scene'],
  [0x6B, 'Castle Courtyard test (hairal_niwa2)', 'other', 'Test maps (MQ debug only)', 'hairal_niwa2_scene'],
  [0x6C, 'Sasatest', 'other', 'Test maps (MQ debug only)', 'sasatest_scene'],
  [0x6D, 'Testroom', 'other', 'Test maps (MQ debug only)', 'testroom_scene'],
];

export const MM_SCENES: SceneName[] = [
  [0x6F, 'South Clock Town', 'hub', 'Clock Town', 'Z2_CLOCKTOWER'],
  [0x6E, 'North Clock Town', 'hub', 'Clock Town', 'Z2_BACKTOWN'],
  [0x6C, 'East Clock Town', 'hub', 'Clock Town', 'Z2_TOWN'],
  [0x6D, 'West Clock Town', 'hub', 'Clock Town', 'Z2_ICHIBA'],
  [0x70, 'Laundry Pool', 'hub', 'Clock Town', 'Z2_ALLEY'],
  [0x19, 'Clock Tower rooftop', 'hub', 'Clock Town', 'Z2_OKUJOU'],
  [0x63, 'Clock Tower interior', 'hub', 'Clock Town', 'Z2_INSIDETOWER'],
  [0x2D, 'Termina Field', 'hub', 'Termina Field and Romani Ranch', 'Z2_00KEIKOKU'],
  [0x22, 'Milk Road', 'hub', 'Termina Field and Romani Ranch', 'Z2_ROMANYMAE'],
  [0x35, 'Romani Ranch', 'hub', 'Termina Field and Romani Ranch', 'Z2_F01'],
  [0x41, 'Doggy Racetrack', 'hub', 'Termina Field and Romani Ranch', 'Z2_F01_B'],
  [0x6A, 'Gorman Track', 'hub', 'Termina Field and Romani Ranch', 'Z2_KOEPONARACE'],
  [0x40, 'Road to Southern Swamp', 'hub', 'Southern Swamp and Woodfall', 'Z2_24KEMONOMITI'],
  [0x45, 'Southern Swamp (poisoned)', 'hub', 'Southern Swamp and Woodfall', 'Z2_20SICHITAI'],
  [0x00, 'Southern Swamp (cleared)', 'hub', 'Southern Swamp and Woodfall', 'Z2_20SICHITAI2'],
  [0x64, 'Woods of Mystery', 'hub', 'Southern Swamp and Woodfall', 'Z2_26SARUNOMORI'],
  [0x2B, 'Deku Palace', 'hub', 'Southern Swamp and Woodfall', 'Z2_22DEKUCITY'],
  [0x46, 'Woodfall', 'hub', 'Southern Swamp and Woodfall', 'Z2_21MITURINMAE'],
  [0x1C, 'Path to Mountain Village', 'hub', 'Snowhead', 'Z2_13HUBUKINOMITI'],
  [0x50, 'Mountain Village (winter)', 'hub', 'Snowhead', 'Z2_10YUKIYAMANOMURA'],
  [0x5A, 'Mountain Village (spring)', 'hub', 'Snowhead', 'Z2_10YUKIYAMANOMURA2'],
  [0x5D, 'Twin Islands (winter)', 'hub', 'Snowhead', 'Z2_17SETUGEN'],
  [0x5E, 'Twin Islands (spring)', 'hub', 'Snowhead', 'Z2_17SETUGEN2'],
  [0x4D, 'Goron Village (winter)', 'hub', 'Snowhead', 'Z2_11GORONNOSATO'],
  [0x48, 'Goron Village (spring)', 'hub', 'Snowhead', 'Z2_11GORONNOSATO2'],
  [0x5B, 'Path to Snowhead', 'hub', 'Snowhead', 'Z2_14YUKIDAMANOMITI'],
  [0x5C, 'Snowhead', 'hub', 'Snowhead', 'Z2_12HAKUGINMAE'],
  [0x6B, 'Goron Racetrack', 'hub', 'Snowhead', 'Z2_GORONRACE'],
  [0x37, 'Great Bay Coast', 'hub', 'Great Bay', 'Z2_30GYOSON'],
  [0x38, 'Zora Cape', 'hub', 'Great Bay', 'Z2_31MISAKI'],
  [0x3B, 'Pirates\' Fortress exterior', 'hub', 'Great Bay', 'Z2_TORIDE'],
  [0x14, 'Pirates\' Fortress (moat and courtyard)', 'hub', 'Great Bay', 'Z2_KAIZOKU'],
  [0x33, 'Zora Hall', 'hub', 'Great Bay', 'Z2_33ZORACITY'],
  [0x4A, 'Waterfall Rapids', 'hub', 'Great Bay', 'Z2_35TAKI'],
  [0x25, 'Pinnacle Rock', 'hub', 'Great Bay', 'Z2_SINKAI'],
  [0x62, 'Great Bay (cutscene)', 'hub', 'Great Bay', 'Z2_KONPEKI_ENT'],
  [0x53, 'Road to Ikana', 'hub', 'Ikana', 'Z2_IKANAMAE'],
  [0x43, 'Ikana Graveyard', 'hub', 'Ikana', 'Z2_BOTI'],
  [0x13, 'Ikana Canyon', 'hub', 'Ikana', 'Z2_IKANA'],
  [0x58, 'Stone Tower', 'hub', 'Ikana', 'Z2_F40'],
  [0x59, 'Stone Tower (inverted)', 'hub', 'Ikana', 'Z2_F41'],
  [0x1B, 'Woodfall Temple', 'adventure', 'Temples', 'Z2_MITURIN'],
  [0x21, 'Snowhead Temple', 'adventure', 'Temples', 'Z2_HAKUGIN'],
  [0x49, 'Great Bay Temple', 'adventure', 'Temples', 'Z2_SEA'],
  [0x16, 'Stone Tower Temple', 'adventure', 'Temples', 'Z2_INISIE_N'],
  [0x18, 'Stone Tower Temple (inverted)', 'adventure', 'Temples', 'Z2_INISIE_R'],
  [0x23, 'Pirates\' Fortress interior', 'adventure', 'Other dungeons', 'Z2_PIRATE'],
  [0x1D, 'Ancient Castle of Ikana', 'adventure', 'Other dungeons', 'Z2_CASTLE'],
  [0x4B, 'Beneath the Well', 'adventure', 'Other dungeons', 'Z2_REDEAD'],
  [0x0C, 'Beneath the Graveyard', 'adventure', 'Other dungeons', 'Z2_HAKASHITA'],
  [0x30, 'Dampé\'s House', 'adventure', 'Other dungeons', 'Z2_DANPEI2TEST'],
  [0x52, 'Deku Shrine', 'adventure', 'Other dungeons', 'Z2_DANPEI'],
  [0x27, 'Swamp Spider House', 'adventure', 'Other dungeons', 'Z2_KINSTA1'],
  [0x28, 'Oceanside Spider House', 'adventure', 'Other dungeons', 'Z2_KINDAN2'],
  [0x60, 'Secret Shrine', 'adventure', 'Other dungeons', 'Z2_RANDOM'],
  [0x1A, 'Clock Tower basement (opening dungeon)', 'adventure', 'Other dungeons', 'Z2_OPENINGDAN'],
  [0x67, 'The Moon', 'adventure', 'The Moon', 'Z2_SOUGEN'],
  [0x2A, 'Moon: Deku trial', 'adventure', 'The Moon', 'Z2_LAST_DEKU'],
  [0x3F, 'Moon: Goron trial', 'adventure', 'The Moon', 'Z2_LAST_GORON'],
  [0x47, 'Moon: Zora trial', 'adventure', 'The Moon', 'Z2_LAST_ZORA'],
  [0x66, 'Moon: Link trial', 'adventure', 'The Moon', 'Z2_LAST_LINK'],
  [0x1F, 'Odolwa\'s Lair', 'boss', 'Boss rooms', 'Z2_MITURIN_BS'],
  [0x44, 'Goht\'s Lair', 'boss', 'Boss rooms', 'Z2_HAKUGIN_BS'],
  [0x5F, 'Gyorg\'s Lair', 'boss', 'Boss rooms', 'Z2_SEA_BS'],
  [0x36, 'Twinmold\'s Lair', 'boss', 'Boss rooms', 'Z2_INISIE_BS'],
  [0x56, 'Igos du Ikana\'s Lair', 'boss', 'Boss rooms', 'Z2_IKNINSIDE'],
  [0x0B, 'Majora\'s Lair', 'boss', 'Boss rooms', 'Z2_LAST_BS'],
  [0x61, 'Stock Pot Inn', 'other', 'Houses, shops and minigames', 'Z2_YADOYA'],
  [0x15, 'Milk Bar', 'other', 'Houses, shops and minigames', 'Z2_MILK_BAR'],
  [0x12, 'The Mayor\'s Residence', 'other', 'Houses, shops and minigames', 'Z2_SONCHONOIE'],
  [0x68, 'Bomb Shop', 'other', 'Houses, shops and minigames', 'Z2_BOMYA'],
  [0x0D, 'Curiosity Shop', 'other', 'Houses, shops and minigames', 'Z2_AYASHIISHOP'],
  [0x34, 'Trading Post', 'other', 'Houses, shops and minigames', 'Z2_8ITEMSHOP'],
  [0x39, 'Lottery Shop', 'other', 'Houses, shops and minigames', 'Z2_TAKARAKUJI'],
  [0x2E, 'Post Office', 'other', 'Houses, shops and minigames', 'Z2_POSTHOUSE'],
  [0x54, 'Swordsman\'s School', 'other', 'Houses, shops and minigames', 'Z2_DOUJOU'],
  [0x17, 'Treasure Chest Shop', 'other', 'Houses, shops and minigames', 'Z2_TAKARAYA'],
  [0x11, 'Honey & Darling\'s Shop', 'other', 'Houses, shops and minigames', 'Z2_BOWLING'],
  [0x20, 'Town Shooting Gallery', 'other', 'Houses, shops and minigames', 'Z2_SYATEKI_MIZU'],
  [0x29, 'Astral Observatory', 'other', 'Houses, shops and minigames', 'Z2_TENMON_DAI'],
  [0x10, 'Romani Ranch house and barn', 'other', 'Houses, shops and minigames', 'Z2_OMOYA'],
  [0x42, 'Cucco Shack', 'other', 'Houses, shops and minigames', 'Z2_F01C'],
  [0x0A, 'Magic Hags\' Potion Shop', 'other', 'Houses, shops and minigames', 'Z2_WITCH_SHOP'],
  [0x57, 'Tourist Information', 'other', 'Houses, shops and minigames', 'Z2_MAP_SHOP'],
  [0x24, 'Swamp Shooting Gallery', 'other', 'Houses, shops and minigames', 'Z2_SYATEKI_MORI'],
  [0x3E, 'Deku King\'s Chamber', 'other', 'Houses, shops and minigames', 'Z2_DEKU_KING'],
  [0x1E, 'Deku Scrub Playground', 'other', 'Houses, shops and minigames', 'Z2_DEKUTES'],
  [0x2C, 'Mountain Smithy', 'other', 'Houses, shops and minigames', 'Z2_KAJIYA'],
  [0x3D, 'Goron Shop', 'other', 'Houses, shops and minigames', 'Z2_GORONSHOP'],
  [0x32, 'Goron Shrine', 'other', 'Houses, shops and minigames', 'Z2_16GORON_HOUSE'],
  [0x2F, 'Marine Research Lab', 'other', 'Houses, shops and minigames', 'Z2_LABO'],
  [0x3C, 'Fisherman\'s Hut', 'other', 'Houses, shops and minigames', 'Z2_FISHERMAN'],
  [0x4C, 'Zora Hall rooms', 'other', 'Houses, shops and minigames', 'Z2_BANDROOM'],
  [0x4E, 'Goron Graveyard', 'other', 'Houses, shops and minigames', 'Z2_GORON_HAKA'],
  [0x4F, 'Sakon\'s Hideout', 'other', 'Houses, shops and minigames', 'Z2_SECOM'],
  [0x51, 'Ghost Hut', 'other', 'Houses, shops and minigames', 'Z2_TOUGITES'],
  [0x55, 'Music Box House', 'other', 'Houses, shops and minigames', 'Z2_MUSICHOUSE'],
  [0x26, 'Fairy\'s Fountain', 'other', 'Houses, shops and minigames', 'Z2_YOUSEI_IZUMI'],
  [0x69, 'Giants\' Chamber', 'other', 'Houses, shops and minigames', 'Z2_KYOJINNOMA'],
  [0x07, 'Grottos', 'other', 'Grottos', 'KAKUSIANA'],
  [0x08, 'Cutscene map (opening forest)', 'other', 'Cutscene maps', 'SPOT00'],
  [0x65, 'Lost Woods (intro)', 'other', 'Cutscene maps', 'Z2_LOST_WOODS'],
];

export const OOT_ACTORS: string[] = [
  'Player', 'ACTOR_UNSET_1', 'En_Test', 'ACTOR_UNSET_3', 'En_GirlA', 'ACTOR_UNSET_5', 'ACTOR_UNSET_6', 'En_Part',
  'En_Light', 'En_Door', 'En_Box', 'Bg_Dy_Yoseizo', 'Bg_Hidan_Firewall', 'En_Poh', 'En_Okuta', 'Bg_Ydan_Sp',
  'En_Bom', 'En_Wallmas', 'En_Dodongo', 'En_Firefly', 'En_Horse', 'En_Item00', 'En_Arrow', 'ACTOR_UNSET_17',
  'En_Elf', 'En_Niw', 'ACTOR_UNSET_1A', 'En_Tite', 'En_Reeba', 'En_Peehat', 'En_Butte', 'ACTOR_UNSET_1F',
  'En_Insect', 'En_Fish', 'ACTOR_UNSET_22', 'En_Holl', 'En_Scene_Change', 'En_Zf', 'En_Hata', 'Boss_Dodongo',
  'Boss_Goma', 'En_Zl1', 'En_Viewer', 'En_Goma', 'Bg_Pushbox', 'En_Bubble', 'Door_Shutter', 'En_Dodojr', 'En_Bdfire',
  'ACTOR_UNSET_31', 'En_Boom', 'En_Torch2', 'En_Bili', 'En_Tp', 'ACTOR_UNSET_36', 'En_St', 'En_Bw', 'En_A_Obj',
  'En_Eiyer', 'En_River_Sound', 'En_Horse_Normal', 'En_Ossan', 'Bg_Treemouth', 'Bg_Dodoago', 'Bg_Hidan_Dalm',
  'Bg_Hidan_Hrock', 'En_Horse_Ganon', 'Bg_Hidan_Rock', 'Bg_Hidan_Rsekizou', 'Bg_Hidan_Sekizou', 'Bg_Hidan_Sima',
  'Bg_Hidan_Syoku', 'En_Xc', 'Bg_Hidan_Curtain', 'Bg_Spot00_Hanebasi', 'En_Mb', 'En_Bombf', 'En_Zl2',
  'Bg_Hidan_Fslift', 'En_OE2', 'Bg_Ydan_Hasi', 'Bg_Ydan_Maruta', 'Boss_Ganondrof', 'ACTOR_UNSET_53', 'En_Am',
  'En_Dekubaba', 'En_M_Fire1', 'En_M_Thunder', 'Bg_Ddan_Jd', 'Bg_Breakwall', 'En_Jj', 'En_Horse_Zelda', 'Bg_Ddan_Kd',
  'Door_Warp1', 'Obj_Syokudai', 'Item_B_Heart', 'En_Dekunuts', 'Bg_Menkuri_Kaiten', 'Bg_Menkuri_Eye', 'En_Vali',
  'Bg_Mizu_Movebg', 'Bg_Mizu_Water', 'Arms_Hook', 'En_fHG', 'Bg_Mori_Hineri', 'En_Bb', 'Bg_Toki_Hikari',
  'En_Yukabyun', 'Bg_Toki_Swd', 'En_Fhg_Fire', 'Bg_Mjin', 'Bg_Hidan_Kousi', 'Door_Toki', 'Bg_Hidan_Hamstep',
  'En_Bird', 'ACTOR_UNSET_73', 'ACTOR_UNSET_74', 'ACTOR_UNSET_75', 'ACTOR_UNSET_76', 'En_Wood02', 'ACTOR_UNSET_78',
  'ACTOR_UNSET_79', 'ACTOR_UNSET_7A', 'ACTOR_UNSET_7B', 'En_Lightbox', 'En_Pu_box', 'ACTOR_UNSET_7E',
  'ACTOR_UNSET_7F', 'En_Trap', 'En_Arow_Trap', 'En_Vase', 'ACTOR_UNSET_83', 'En_Ta', 'En_Tk', 'Bg_Mori_Bigst',
  'Bg_Mori_Elevator', 'Bg_Mori_Kaitenkabe', 'Bg_Mori_Rakkatenjo', 'En_Vm', 'Demo_Effect', 'Demo_Kankyo',
  'Bg_Hidan_Fwbig', 'En_Floormas', 'En_Heishi1', 'En_Rd', 'En_Po_Sisters', 'Bg_Heavy_Block', 'Bg_Po_Event',
  'Obj_Mure', 'En_Sw', 'Boss_Fd', 'Object_Kankyo', 'En_Du', 'En_Fd', 'En_Horse_Link_Child', 'Door_Ana',
  'Bg_Spot02_Objects', 'Bg_Haka', 'Magic_Wind', 'Magic_Fire', 'ACTOR_UNSET_A0', 'En_Ru1', 'Boss_Fd2', 'En_Fd_Fire',
  'En_Dh', 'En_Dha', 'En_Rl', 'En_Encount1', 'Demo_Du', 'Demo_Im', 'Demo_Tre_Lgt', 'En_Fw', 'Bg_Vb_Sima',
  'En_Vb_Ball', 'Bg_Haka_Megane', 'Bg_Haka_MeganeBG', 'Bg_Haka_Ship', 'Bg_Haka_Sgami', 'ACTOR_UNSET_B2',
  'En_Heishi2', 'En_Encount2', 'En_Fire_Rock', 'En_Brob', 'Mir_Ray', 'Bg_Spot09_Obj', 'Bg_Spot18_Obj', 'Boss_Va',
  'Bg_Haka_Tubo', 'Bg_Haka_Trap', 'Bg_Haka_Huta', 'Bg_Haka_Zou', 'Bg_Spot17_Funen', 'En_Syateki_Itm',
  'En_Syateki_Man', 'En_Tana', 'En_Nb', 'Boss_Mo', 'En_Sb', 'En_Bigokuta', 'En_Karebaba', 'Bg_Bdan_Objects',
  'Demo_Sa', 'Demo_Go', 'En_In', 'En_Tr', 'Bg_Spot16_Bombstone', 'ACTOR_UNSET_CE', 'Bg_Hidan_Kowarerukabe',
  'Bg_Bombwall', 'Bg_Spot08_Iceblock', 'En_Ru2', 'Obj_Dekujr', 'Bg_Mizu_Uzu', 'Bg_Spot06_Objects', 'Bg_Ice_Objects',
  'Bg_Haka_Water', 'ACTOR_UNSET_D8', 'En_Ma2', 'En_Bom_Chu', 'En_Horse_Game_Check', 'Boss_Tw', 'En_Rr', 'En_Ba',
  'En_Bx', 'En_Anubice', 'En_Anubice_Fire', 'Bg_Mori_Hashigo', 'Bg_Mori_Hashira4', 'Bg_Mori_Idomizu',
  'Bg_Spot16_Doughnut', 'Bg_Bdan_Switch', 'En_Ma1', 'Boss_Ganon', 'Boss_Sst', 'ACTOR_UNSET_EA', 'ACTOR_UNSET_EB',
  'En_Ny', 'En_Fr', 'Item_Shield', 'Bg_Ice_Shelter', 'En_Ice_Hono', 'Item_Ocarina', 'ACTOR_UNSET_F2',
  'ACTOR_UNSET_F3', 'Magic_Dark', 'Demo_6K', 'En_Anubice_Tag', 'Bg_Haka_Gate', 'Bg_Spot15_Saku', 'Bg_Jya_Goroiwa',
  'Bg_Jya_Zurerukabe', 'ACTOR_UNSET_FB', 'Bg_Jya_Cobra', 'Bg_Jya_Kanaami', 'Fishing', 'Obj_Oshihiki',
  'Bg_Gate_Shutter', 'Eff_Dust', 'Bg_Spot01_Fusya', 'Bg_Spot01_Idohashira', 'Bg_Spot01_Idomizu', 'Bg_Po_Syokudai',
  'Bg_Ganon_Otyuka', 'Bg_Spot15_Rrbox', 'Bg_Umajump', 'ACTOR_UNSET_109', 'Arrow_Fire', 'Arrow_Ice', 'Arrow_Light',
  'ACTOR_UNSET_10D', 'ACTOR_UNSET_10E', 'Item_Etcetera', 'Obj_Kibako', 'Obj_Tsubo', 'En_Wonder_Item', 'En_Ik',
  'Demo_Ik', 'En_Skj', 'En_Skjneedle', 'En_G_Switch', 'Demo_Ext', 'Demo_Shd', 'En_Dns', 'Elf_Msg', 'En_Honotrap',
  'En_Tubo_Trap', 'Obj_Ice_Poly', 'Bg_Spot03_Taki', 'Bg_Spot07_Taki', 'En_Fz', 'En_Po_Relay', 'Bg_Relay_Objects',
  'En_Diving_Game', 'En_Kusa', 'Obj_Bean', 'Obj_Bombiwa', 'ACTOR_UNSET_128', 'ACTOR_UNSET_129', 'Obj_Switch',
  'Obj_Elevator', 'Obj_Lift', 'Obj_Hsblock', 'En_Okarina_Tag', 'En_Yabusame_Mark', 'En_Goroiwa', 'En_Ex_Ruppy',
  'En_Toryo', 'En_Daiku', 'ACTOR_UNSET_134', 'En_Nwc', 'En_Blkobj', 'Item_Inbox', 'En_Ge1', 'Obj_Blockstop',
  'En_Sda', 'En_Clear_Tag', 'En_Niw_Lady', 'En_Gm', 'En_Ms', 'En_Hs', 'Bg_Ingate', 'En_Kanban', 'En_Heishi3',
  'En_Syateki_Niw', 'En_Attack_Niw', 'Bg_Spot01_Idosoko', 'En_Sa', 'En_Wonder_Talk', 'Bg_Gjyo_Bridge', 'En_Ds',
  'En_Mk', 'En_Bom_Bowl_Man', 'En_Bom_Bowl_Pit', 'En_Owl', 'En_Ishi', 'Obj_Hana', 'Obj_Lightswitch', 'Obj_Mure2',
  'En_Go', 'En_Fu', 'ACTOR_UNSET_154', 'En_Changer', 'Bg_Jya_Megami', 'Bg_Jya_Lift', 'Bg_Jya_Bigmirror',
  'Bg_Jya_Bombchuiwa', 'Bg_Jya_Amishutter', 'Bg_Jya_Bombiwa', 'Bg_Spot18_Basket', 'ACTOR_UNSET_15D',
  'En_Ganon_Organ', 'En_Siofuki', 'En_Stream', 'ACTOR_UNSET_161', 'En_Mm', 'En_Ko', 'En_Kz', 'En_Weather_Tag',
  'Bg_Sst_Floor', 'En_Ani', 'En_Ex_Item', 'Bg_Jya_Ironobj', 'En_Js', 'En_Jsjutan', 'En_Cs', 'En_Md', 'En_Hy',
  'En_Ganon_Mant', 'En_Okarina_Effect', 'En_Mag', 'Door_Gerudo', 'Elf_Msg2', 'Demo_Gt', 'En_Po_Field', 'Efc_Erupc',
  'Bg_Zg', 'En_Heishi4', 'En_Zl3', 'Boss_Ganon2', 'En_Kakasi', 'En_Takara_Man', 'Obj_Makeoshihiki', 'Oceff_Spot',
  'End_Title', 'ACTOR_UNSET_180', 'En_Torch', 'Demo_Ec', 'Shot_Sun', 'En_Dy_Extra', 'En_Wonder_Talk2', 'En_Ge2',
  'Obj_Roomtimer', 'En_Ssh', 'En_Sth', 'Oceff_Wipe', 'Oceff_Storm', 'En_Weiyer', 'Bg_Spot05_Soko', 'Bg_Jya_1flift',
  'Bg_Jya_Haheniron', 'Bg_Spot12_Gate', 'Bg_Spot12_Saku', 'En_Hintnuts', 'En_Nutsball', 'Bg_Spot00_Break',
  'En_Shopnuts', 'En_It', 'En_GeldB', 'Oceff_Wipe2', 'Oceff_Wipe3', 'En_Niw_Girl', 'En_Dog', 'En_Si',
  'Bg_Spot01_Objects2', 'Obj_Comb', 'Bg_Spot11_Bakudankabe', 'Obj_Kibako2', 'En_Dnt_Demo', 'En_Dnt_Jiji',
  'En_Dnt_Nomal', 'En_Guest', 'Bg_Bom_Guard', 'En_Hs2', 'Demo_Kekkai', 'Bg_Spot08_Bakudankabe',
  'Bg_Spot17_Bakudankabe', 'ACTOR_UNSET_1AA', 'Obj_Mure3', 'En_Tg', 'En_Mu', 'En_Go2', 'En_Wf', 'En_Skb', 'Demo_Gj',
  'Demo_Geff', 'Bg_Gnd_Firemeiro', 'Bg_Gnd_Darkmeiro', 'Bg_Gnd_Soulmeiro', 'Bg_Gnd_Nisekabe', 'Bg_Gnd_Iceblock',
  'En_Gb', 'En_Gs', 'Bg_Mizu_Bwall', 'Bg_Mizu_Shutter', 'En_Daiku_Kakariko', 'Bg_Bowl_Wall', 'En_Wall_Tubo',
  'En_Po_Desert', 'En_Crow', 'Door_Killer', 'Bg_Spot11_Oasis', 'Bg_Spot18_Futa', 'Bg_Spot18_Shutter', 'En_Ma3',
  'En_Cow', 'Bg_Ice_Turara', 'Bg_Ice_Shutter', 'En_Kakasi2', 'En_Kakasi3', 'Oceff_Wipe4', 'En_Eg',
  'Bg_Menkuri_Nisekabe', 'En_Zo', 'Obj_Makekinsuta', 'En_Ge3', 'Obj_Timeblock', 'Obj_Hamishi', 'En_Zl4', 'En_Mm2',
  'Bg_Jya_Block', 'Obj_Warp2block',
];

export const MM_ACTORS: string[] = [
  'Player', 'En_Test', 'En_GirlA', 'En_Part', 'En_Light', 'En_Door', 'En_Box', 'En_Pametfrog', 'En_Okuta', 'En_Bom',
  'En_Wallmas', 'En_Dodongo', 'En_Firefly', 'En_Horse', 'En_Item00', 'En_Arrow', 'En_Elf', 'En_Niw', 'En_Tite',
  'ACTOR_UNSET_13', 'En_Peehat', 'En_Butte', 'En_Insect', 'En_Fish', 'En_Holl', 'En_Dinofos', 'En_Hata', 'En_Zl1',
  'En_Viewer', 'En_Bubble', 'Door_Shutter', 'ACTOR_UNSET_1F', 'En_Boom', 'En_Torch2', 'En_Minifrog',
  'ACTOR_UNSET_23', 'En_St', 'ACTOR_UNSET_25', 'En_A_Obj', 'Obj_Wturn', 'En_River_Sound', 'ACTOR_UNSET_29',
  'En_Ossan', 'ACTOR_UNSET_2B', 'ACTOR_UNSET_2C', 'En_Famos', 'ACTOR_UNSET_2E', 'En_Bombf', 'ACTOR_UNSET_30',
  'ACTOR_UNSET_31', 'En_Am', 'En_Dekubaba', 'En_M_Fire1', 'En_M_Thunder', 'Bg_Breakwall', 'ACTOR_UNSET_37',
  'Door_Warp1', 'Obj_Syokudai', 'Item_B_Heart', 'En_Dekunuts', 'En_Bbfall', 'Arms_Hook', 'En_Bb', 'Bg_Keikoku_Spr',
  'ACTOR_UNSET_40', 'En_Wood02', 'ACTOR_UNSET_42', 'En_Death', 'En_Minideath', 'ACTOR_UNSET_45', 'ACTOR_UNSET_46',
  'En_Vm', 'Demo_Effect', 'Demo_Kankyo', 'En_Floormas', 'ACTOR_UNSET_4B', 'En_Rd', 'Bg_F40_Flift',
  'ACTOR_BG_HEAVY_BLOCK', 'Obj_Mure', 'En_Sw', 'Object_Kankyo', 'ACTOR_UNSET_52', 'ACTOR_UNSET_53',
  'En_Horse_Link_Child', 'Door_Ana', 'ACTOR_UNSET_56', 'ACTOR_UNSET_57', 'ACTOR_UNSET_58', 'ACTOR_UNSET_59',
  'ACTOR_UNSET_5A', 'En_Encount1', 'Demo_Tre_Lgt', 'ACTOR_UNSET_5D', 'ACTOR_UNSET_5E', 'En_Encount2', 'En_Fire_Rock',
  'Bg_Ctower_Rot', 'Mir_Ray', 'ACTOR_UNSET_63', 'En_Sb', 'En_Bigslime', 'En_Karebaba', 'En_In', 'ACTOR_UNSET_68',
  'En_Ru', 'En_Bom_Chu', 'En_Horse_Game_Check', 'En_Rr', 'ACTOR_UNSET_6D', 'ACTOR_UNSET_6E', 'ACTOR_UNSET_6F',
  'ACTOR_UNSET_70', 'ACTOR_UNSET_71', 'ACTOR_UNSET_72', 'En_Fr', 'ACTOR_UNSET_74', 'ACTOR_UNSET_75',
  'ACTOR_UNSET_76', 'ACTOR_UNSET_77', 'ACTOR_UNSET_78', 'En_Fishing', 'Obj_Oshihiki', 'Eff_Dust', 'Bg_Umajump',
  'Arrow_Fire', 'Arrow_Ice', 'Arrow_Light', 'Item_Etcetera', 'Obj_Kibako', 'Obj_Tsubo', 'ACTOR_UNSET_83', 'En_Ik',
  'ACTOR_UNSET_85', 'ACTOR_UNSET_86', 'ACTOR_UNSET_87', 'ACTOR_UNSET_88', 'Demo_Shd', 'En_Dns', 'Elf_Msg',
  'En_Honotrap', 'En_Tubo_Trap', 'Obj_Ice_Poly', 'En_Fz', 'En_Kusa', 'Obj_Bean', 'Obj_Bombiwa', 'Obj_Switch',
  'ACTOR_UNSET_94', 'Obj_Lift', 'Obj_Hsblock', 'En_Okarina_Tag', 'ACTOR_UNSET_98', 'En_Goroiwa', 'ACTOR_UNSET_9A',
  'ACTOR_UNSET_9B', 'En_Daiku', 'En_Nwc', 'Item_Inbox', 'En_Ge1', 'Obj_Blockstop', 'En_Sda', 'En_Clear_Tag',
  'ACTOR_UNSET_A3', 'En_Gm', 'En_Ms', 'En_Hs', 'Bg_Ingate', 'En_Kanban', 'ACTOR_UNSET_A9', 'En_Attack_Niw',
  'ACTOR_UNSET_AB', 'ACTOR_UNSET_AC', 'ACTOR_UNSET_AD', 'En_Mk', 'En_Owl', 'En_Ishi', 'Obj_Hana', 'Obj_Lightswitch',
  'Obj_Mure2', 'ACTOR_UNSET_B4', 'En_Fu', 'ACTOR_UNSET_B6', 'ACTOR_UNSET_B7', 'En_Stream', 'En_Mm', 'ACTOR_UNSET_BA',
  'ACTOR_UNSET_BB', 'En_Weather_Tag', 'En_Ani', 'ACTOR_UNSET_BE', 'En_Js', 'ACTOR_UNSET_C0', 'ACTOR_UNSET_C1',
  'ACTOR_UNSET_C2', 'ACTOR_UNSET_C3', 'En_Okarina_Effect', 'En_Mag', 'Elf_Msg2', 'Bg_F40_Swlift', 'ACTOR_UNSET_C8',
  'ACTOR_UNSET_C9', 'En_Kakasi', 'Obj_Makeoshihiki', 'Oceff_Spot', 'ACTOR_UNSET_CD', 'En_Torch', 'ACTOR_UNSET_CF',
  'Shot_Sun', 'ACTOR_UNSET_D1', 'ACTOR_UNSET_D2', 'Obj_Roomtimer', 'En_Ssh', 'ACTOR_UNSET_D5', 'Oceff_Wipe',
  'Oceff_Storm', 'Obj_Demo', 'En_Minislime', 'En_Nutsball', 'ACTOR_UNSET_DB', 'ACTOR_UNSET_DC', 'ACTOR_UNSET_DD',
  'ACTOR_UNSET_DE', 'Oceff_Wipe2', 'Oceff_Wipe3', 'ACTOR_UNSET_E1', 'En_Dg', 'En_Si', 'Obj_Comb', 'Obj_Kibako2',
  'ACTOR_UNSET_E6', 'En_Hs2', 'Obj_Mure3', 'En_Tg', 'ACTOR_UNSET_EA', 'ACTOR_UNSET_EB', 'En_Wf', 'En_Skb',
  'ACTOR_UNSET_EE', 'En_Gs', 'Obj_Sound', 'En_Crow', 'ACTOR_UNSET_F2', 'En_Cow', 'ACTOR_UNSET_F4', 'ACTOR_UNSET_F5',
  'Oceff_Wipe4', 'ACTOR_UNSET_F7', 'En_Zo', 'Obj_Makekinsuta', 'En_Ge3', 'ACTOR_UNSET_FB', 'Obj_Hamishi', 'En_Zl4',
  'En_Mm2', 'ACTOR_UNSET_FF', 'Door_Spiral', 'ACTOR_UNSET_101', 'Obj_Pzlblock', 'Obj_Toge', 'ACTOR_UNSET_104',
  'Obj_Armos', 'Obj_Boyo', 'ACTOR_UNSET_107', 'ACTOR_UNSET_108', 'En_Grasshopper', 'ACTOR_UNSET_10A', 'Obj_Grass',
  'Obj_Grass_Carry', 'Obj_Grass_Unit', 'ACTOR_UNSET_10E', 'ACTOR_UNSET_10F', 'Bg_Fire_Wall', 'En_Bu', 'En_Encount3',
  'En_Jso', 'Obj_Chikuwa', 'En_Knight', 'En_Warp_tag', 'En_Aob_01', 'En_Boj_01', 'En_Boj_02', 'En_Boj_03',
  'En_Encount4', 'En_Bom_Bowl_Man', 'En_Syateki_Man', 'ACTOR_UNSET_11E', 'Bg_Icicle', 'En_Syateki_Crow', 'En_Boj_04',
  'En_Cne_01', 'En_Bba_01', 'En_Bji_01', 'Bg_Spdweb', 'ACTOR_UNSET_126', 'ACTOR_UNSET_127', 'En_Mt_tag', 'Boss_01',
  'Boss_02', 'Boss_03', 'Boss_04', 'Boss_05', 'Boss_06', 'Boss_07', 'Bg_Dy_Yoseizo', 'ACTOR_UNSET_131', 'En_Boj_05',
  'ACTOR_UNSET_133', 'ACTOR_UNSET_134', 'En_Sob1', 'ACTOR_UNSET_136', 'ACTOR_UNSET_137', 'En_Go', 'ACTOR_UNSET_139',
  'En_Raf', 'Obj_Funen', 'Obj_Raillift', 'Bg_Numa_Hana', 'Obj_Flowerpot', 'Obj_Spinyroll', 'Dm_Hina',
  'En_Syateki_Wf', 'Obj_Skateblock', 'Obj_Iceblock', 'En_Bigpamet', 'En_Syateki_Dekunuts', 'Elf_Msg3', 'En_Fg',
  'Dm_Ravine', 'Dm_Sa', 'En_Slime', 'En_Pr', 'Obj_Toudai', 'Obj_Entotu', 'Obj_Bell', 'En_Syateki_Okuta',
  'ACTOR_UNSET_150', 'Obj_Shutter', 'Dm_Zl', 'En_Elfgrp', 'Dm_Tsg', 'En_Baguo', 'Obj_Vspinyroll', 'Obj_Smork',
  'En_Test2', 'En_Test3', 'En_Test4', 'En_Bat', 'En_Sekihi', 'En_Wiz', 'En_Wiz_Brock', 'En_Wiz_Fire', 'Eff_Change',
  'Dm_Statue', 'Obj_Fireshield', 'Bg_Ladder', 'En_Mkk', 'Demo_Getitem', 'ACTOR_UNSET_166', 'En_Dnb', 'En_Dnh',
  'En_Dnk', 'En_Dnq', 'ACTOR_UNSET_16B', 'Bg_Keikoku_Saku', 'Obj_Hugebombiwa', 'En_Firefly2', 'En_Rat',
  'En_Water_Effect', 'En_Kusa2', 'Bg_Spout_Fire', 'ACTOR_UNSET_173', 'Bg_Dblue_Movebg', 'En_Dy_Extra', 'En_Bal',
  'En_Ginko_Man', 'En_Warp_Uzu', 'Obj_Driftice', 'En_Look_Nuts', 'En_Mushi2', 'En_Fall', 'En_Mm3', 'Bg_Crace_Movebg',
  'En_Dno', 'En_Pr2', 'En_Prz', 'En_Jso2', 'Obj_Etcetera', 'En_Egol', 'Obj_Mine', 'Obj_Purify', 'En_Tru', 'En_Trt',
  'ACTOR_UNSET_189', 'ACTOR_UNSET_18A', 'En_Test5', 'En_Test6', 'En_Az', 'En_Estone', 'Bg_Hakugin_Post',
  'Dm_Opstage', 'Dm_Stk', 'Dm_Char00', 'Dm_Char01', 'Dm_Char02', 'Dm_Char03', 'Dm_Char04', 'Dm_Char05', 'Dm_Char06',
  'Dm_Char07', 'Dm_Char08', 'Dm_Char09', 'Obj_Tokeidai', 'ACTOR_UNSET_19D', 'En_Mnk', 'En_Egblock', 'En_Guard_Nuts',
  'Bg_Hakugin_Bombwall', 'Obj_Tokei_Tobira', 'Bg_Hakugin_Elvpole', 'En_Ma4', 'En_Twig', 'En_Po_Fusen', 'En_Door_Etc',
  'En_Bigokuta', 'Bg_Icefloe', 'Obj_Ocarinalift', 'En_Time_Tag', 'Bg_Open_Shutter', 'Bg_Open_Spot', 'Bg_Fu_Kaiten',
  'Obj_Aqua', 'En_Elforg', 'En_Elfbub', 'ACTOR_UNSET_1B2', 'En_Fu_Mato', 'En_Fu_Kago', 'En_Osn', 'Bg_Ctower_Gear',
  'En_Trt2', 'Obj_Tokei_Step', 'Bg_Lotus', 'En_Kame', 'Obj_Takaraya_Wall', 'Bg_Fu_Mizu', 'En_Sellnuts',
  'Bg_Dkjail_Ivy', 'ACTOR_UNSET_1BF', 'Obj_Visiblock', 'En_Takaraya', 'En_Tsn', 'En_Ds2n', 'En_Fsn', 'En_Shn',
  'ACTOR_UNSET_1C6', 'En_Stop_heishi', 'Obj_Bigicicle', 'En_Lift_Nuts', 'En_Tk', 'ACTOR_UNSET_1CB', 'Bg_Market_Step',
  'Obj_Lupygamelift', 'En_Test7', 'Obj_Lightblock', 'Mir_Ray2', 'En_Wdhand', 'En_Gamelupy', 'Bg_Danpei_Movebg',
  'En_Snowwd', 'En_Pm', 'En_Gakufu', 'Elf_Msg4', 'Elf_Msg5', 'En_Col_Man', 'En_Talk_Gibud', 'En_Giant',
  'Obj_Snowball', 'Boss_Hakugin', 'En_Gb2', 'En_Onpuman', 'Bg_Tobira01', 'En_Tag_Obj', 'Obj_Dhouse', 'Obj_Hakaisi',
  'Bg_Hakugin_Switch', 'ACTOR_UNSET_1E5', 'En_Snowman', 'TG_Sw', 'En_Po_Sisters', 'En_Pp', 'En_Hakurock',
  'En_Hanabi', 'Obj_Dowsing', 'Obj_Wind', 'En_Racedog', 'En_Kendo_Js', 'Bg_Botihasira', 'En_Fish2', 'En_Pst',
  'En_Poh', 'Obj_Spidertent', 'En_Zoraegg', 'En_Kbt', 'En_Gg', 'En_Maruta', 'Obj_Snowball2', 'En_Gg2', 'Obj_Ghaka',
  'En_Dnp', 'En_Dai', 'Bg_Goron_Oyu', 'En_Kgy', 'En_Invadepoh', 'En_Gk', 'En_An', 'ACTOR_UNSET_203', 'En_Bee',
  'En_Ot', 'En_Dragon', 'Obj_Dora', 'En_Bigpo', 'Obj_Kendo_Kanban', 'Obj_Hariko', 'En_Sth', 'Bg_Sinkai_Kabe',
  'Bg_Haka_Curtain', 'Bg_Kin2_Bombwall', 'Bg_Kin2_Fence', 'Bg_Kin2_Picture', 'Bg_Kin2_Shelf', 'En_Rail_Skb', 'En_Jg',
  'En_Tru_Mt', 'Obj_Um', 'En_Neo_Reeba', 'Bg_Mbar_Chair', 'Bg_Ikana_Block', 'Bg_Ikana_Mirror', 'Bg_Ikana_Rotaryroom',
  'Bg_Dblue_Balance', 'Bg_Dblue_Waterfall', 'En_Kaizoku', 'En_Ge2', 'En_Ma_Yts', 'En_Ma_Yto', 'Obj_Tokei_Turret',
  'Bg_Dblue_Elevator', 'Obj_Warpstone', 'En_Zog', 'Obj_Rotlift', 'Obj_Jg_Gakki', 'Bg_Inibs_Movebg', 'En_Zot',
  'Obj_Tree', 'Obj_Y2lift', 'Obj_Y2shutter', 'Obj_Boat', 'Obj_Taru', 'Obj_Hunsui', 'En_Jc_Mato', 'Mir_Ray3',
  'En_Zob', 'Elf_Msg6', 'Obj_Nozoki', 'En_Toto', 'En_Railgibud', 'En_Baba', 'En_Suttari', 'En_Zod', 'En_Kujiya',
  'En_Geg', 'Obj_Kinoko', 'Obj_Yasi', 'En_Tanron1', 'En_Tanron2', 'En_Tanron3', 'Obj_Chan', 'En_Zos', 'En_S_Goro',
  'En_Nb', 'En_Ja', 'Bg_F40_Block', 'Bg_F40_Switch', 'En_Po_Composer', 'En_Guruguru', 'Oceff_Wipe5',
  'En_Stone_heishi', 'Oceff_Wipe6', 'En_Scopenuts', 'En_Scopecrow', 'Oceff_Wipe7', 'Eff_Kamejima_Wave', 'En_Hg',
  'En_Hgo', 'En_Zov', 'En_Ah', 'Obj_Hgdoor', 'Bg_Ikana_Bombwall', 'Bg_Ikana_Ray', 'Bg_Ikana_Shutter',
  'Bg_Haka_Bombwall', 'Bg_Haka_Tomb', 'En_Sc_Ruppe', 'Bg_Iknv_Doukutu', 'Bg_Iknv_Obj', 'En_Pamera', 'Obj_HsStump',
  'En_Hidden_Nuts', 'En_Zow', 'En_Talk', 'En_Al', 'En_Tab', 'En_Nimotsu', 'En_Hit_Tag', 'En_Ruppecrow', 'En_Tanron4',
  'En_Tanron5', 'En_Tanron6', 'En_Daiku2', 'En_Muto', 'En_Baisen', 'En_Heishi', 'En_Demo_heishi', 'En_Dt', 'En_Cha',
  'Obj_Dinner', 'Eff_Lastday', 'Bg_Ikana_Dharma', 'En_Akindonuts', 'Eff_Stk', 'En_Ig', 'En_Rg', 'En_Osk', 'En_Sth2',
  'En_Yb', 'En_Rz', 'En_Scopecoin', 'En_Bjt', 'En_Bomjima', 'En_Bomjimb', 'En_Bombers', 'En_Bombers2', 'En_Bombal',
  'Obj_Moon_Stone', 'Obj_Mu_Pict', 'Bg_Ikninside', 'Eff_Zoraband', 'Obj_Kepn_Koya', 'Obj_Usiyane', 'En_Nnh',
  'Obj_Kzsaku', 'Obj_Milk_Bin', 'En_Kitan', 'Bg_Astr_Bombwall', 'Bg_Iknin_Susceil', 'En_Bsb', 'En_Recepgirl',
  'En_Thiefbird', 'En_Jgame_Tsn', 'Obj_Jgame_Light', 'Obj_Yado', 'Demo_Syoten', 'Demo_Moonend', 'Bg_Lbfshot',
  'Bg_Last_Bwall', 'En_And', 'En_Invadepoh_Demo', 'Obj_Danpeilift', 'En_Fall2', 'Dm_Al', 'Dm_An', 'Dm_Ah', 'Dm_Nb',
  'En_Drs', 'En_Ending_Hero', 'Dm_Bal', 'En_Paper', 'En_Hint_Skb', 'Dm_Tag', 'En_Bh', 'En_Ending_Hero2',
  'En_Ending_Hero3', 'En_Ending_Hero4', 'En_Ending_Hero5', 'En_Ending_Hero6', 'Dm_Gm', 'Obj_Swprize',
  'En_Invisible_Ruppe', 'Obj_Ending', 'En_Rsn',
];
